#!/bin/bash

SUBLIME_USER_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages/User"

mkdir -p "$SUBLIME_USER_DIR"

pushd "$SUBLIME_USER_DIR" > /dev/null

rm -f Preferences.sublime-settings
ln -s ~/.sublime-text/Preferences.sublime-settings .

rm -f Default\ \(OSX\)\.sublime-keymap
ln -s ~/.sublime-text/Default\ \(OSX\)\.sublime-keymap .

rm -f ApplySyntax.sublime-settings
ln -s ~/.sublime-text/ApplySyntax.sublime-settings .

rm -f Ruby-Quotes.tmPreferences
ln -s ~/.sublime-text/Ruby-Quotes.tmPreferences .

popd > /dev/null